# for Android environment
name: NDK CI (for Android)

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        edition:
          - YANEURAOU_ENGINE_MATERIAL9 # 💡 これが「たけわらべ」の定義です！

    steps:
      - name: Checkout own repository
        uses: actions/checkout@v3
        with:
          path: main

      - name: Setup Android NDK r23b
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r23b

      - name: Fix script permissions
        run: chmod +x ./main/script/android_build.sh

      - name: Execute android_build.sh
        run: |
          cd main
          ./script/android_build.sh -e ${{ matrix.edition }}

      - name: Upload Takewarabe Engine
        uses: actions/upload-artifact@v4
        with:
          name: takewarabe-android-final
          path: ./main/build/android/**/*
