# for Android environment
name: NDK CI (for Android)

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout own repository
        uses: actions/checkout@v3
        with:
          path: main

      - name: Setup Android NDK r23b
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r23b

      - name: Direct ndk-build
        run: |
          cd main/src
          # スクリプトを通さず、直接NDKビルドを走らせる
          ndk-build APP_BUILD_SCRIPT=Android.mk NDK_APPLICATION_MK=Application.mk YANEURAOU_EDITION=YANEURAOU_ENGINE_NNUE

      - name: Upload Anything
        uses: actions/upload-artifact@v4
        with:
          name: takewarabe-android_FINAL
          path: |
            ./main/**/libs/**/*
            ./main/**/obj/**/*
            ./main/src/obj/**/*
            ./main/src/libs/**/*
